### ISSUE TITLE
XMigra::VersionControlError when upgrading xmigra to version 1.6.0

### ISSUE THREAD

**Issue by scotthew** [rtweeks/xmigra#13]
**Environment:**
 - Windows 10
 - tortoise svn command line tools

```
svn --version
svn, version 1.9.3 (r1718519)
   compiled Dec 13 2015, 15:47:16 on x86-microsoft-windows
```

Build works fine with xmigra 1.5.1.

**Repro:**
 - Upgraded to to xmigra 1.6.0
 - Run same command displayed below.

Build command output:
```
running command "ruby "C:\Ruby21-x64\bin\xmigra" upgrade "--source=<Path to source>" -o "<output path>\conversation.2-debug-schema.sql""
The system cannot find the path specified.
Subversion command failed with exit code 1 (XMigra::VersionControlError)
```

**Comment by rtweeks** [comment]
Ok, I'll open it as a bug and get to ASAP.

**Comment by scotthew** [comment]
I did a tiny bit of testing and the svn.rb line 32ish output is comming back as empty string.  It feels like a linux path vs windows path issue (i.e c:\path\ vs c:/path/).

```
        cmd_str = cmd_parts.join(' ')
        output = `#{cmd_str}`
```

Not sure if this helps.  Let me know if you want to do a debug sessions.

**Comment by rtweeks** [comment]
Yeah, I'm pretty sure it's the new version of that, which looks like:

@@ -31,7 +31,7 @@ module XMigra
         )
         cmd_str = cmd_parts.join(' ')

-        output = `#{cmd_str}`
+        output = `#{cmd_str} 2>/dev/null`
         raise(VersionControlError, "Subversion command failed with exit
code #{$?.exitstatus}") unless $?.success?
         return output if raw_result && !no_result
         return REXML::Document.new(output) unless no_result

Windows won't like that 2>/dev/null 🙄

**Comment by rtweeks** [comment]
I've published version 1.6.1, which should fix this issue.  I don't have a test platform, so if you test and it's still an issue, please comment back and I try to find a test environment I can use.  I just don't want to hold anyone up waiting for me to put a testing environment together.

**Comment by scotthew** [comment]
```
>  ruby "C:\Ruby21-x64\bin\xmigra" upgrade --production "--source=C:\db\conv" -o "C:\db\Release\DBScripts\\conversation.2-schema.sql"
>  svn: E720087: Can't check path 'C:\DB\bin\Release\NUL': The parameter is incorrect.  
>  Subversion command failed with exit code 1 (XMigra::VersionControlError)
```

**Comment by rtweeks** [comment]
Sorry about that mental lapse.  I've created a new branch off master called `hotfix/issue-13.1`.  If you can check that out and try it against your XMigra schema I'd really appreciate it.  From your XMigra schema root, try:
```
ruby -I%XMIGRA_DIR%\lib %XMIGRA_DIR%\bin\xmigra upgrade --production
```
(where `XMIGRA_DIR` is the set to the location of the `hotfix/issue-13.1` working tree)

**Comment by scotthew** [comment]
Yes that worked.  I was able to run the command above using the hotfix/issue-13.1 working tree.  I also put the svn.rb changes from the working tree directly into the ruby gem 1.6.1 folder and rebuilt and everything worked as expected.

**Comment by rtweeks** [comment]
Version 1.6.2 is released as the fix for this issue.
